

spring:
  application:
    name: mcp-client

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:${SPRING_AI_OPENAI_API_KEY:}}


    mcp:
      client:
        sse:
          connections:
            boardgamedb:
              url: http://localhost:3001

        toolcallback:
          enabled: true
