spring.application.name=Board Game Buddy
spring.servlet.multipart.max-file-size=10MB

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.image.options.model=gpt-image-1
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.collection-name=board-game-buddy

# Levanta compose.yaml (qdrant, jaeger) en desarrollo si Docker está disponible
spring.docker.compose.enabled=true

management.endpoints.web.exposure.include=health,metrics,prometheus
management.tracing.sampling.probability=1.0

otlp.tracing.url=http://localhost:4317


### Not recommended for production
#spring.ai.chat.client.observations.include-input=true
