<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.joedayz</groupId>
    <artifactId>fase5-mcp</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>Fase 5 MCP</name>

    <modules>
        <module>fase5-mcp-provider</module>
        <module>fase5-mcp-consumer</module>
    </modules>
</project>

