server:
  port: 8081

spring:
  application:
    name: springai-workshop-116-weather-mcp-server
  ai:
    mcp:
      server:
        name: weather-service
        version: 1.0.0
        type: SYNC

logging:
  level:
    io.modelcontextprotocol: INFO
