spring.application.name=RagApp

spring.ai.openai.api-key=${OPENAI_API_KEY:}
spring.ai.openai.chat.options.model=gpt-4o

spring.ai.vectorstore.mongodb.initialize-schema=true

spring.data.mongodb.uri=mongodb://localhost:27017/rag?directConnection=true
spring.data.mongodb.database=rag
