# Configuración del puerto
quarkus.http.port=8080

# Configuración de OpenAI
# TODO: Descomentar y configurar
# ia.openai.key=${OPENAI_API_KEY:}
# ia.openai.base=https://api.openai.com/v1
# ia.openai.model=gpt-3.5-turbo
# ia.openai.max-tokens=500
# ia.openai.timeout=30s

# Configuración de Anthropic
# TODO: Descomentar y configurar
# ia.anthropic.key=${ANTHROPIC_API_KEY:}
# ia.anthropic.base=https://api.anthropic.com/v1
# ia.anthropic.model=claude-3-haiku-20240307
# ia.anthropic.max-tokens=500
# ia.anthropic.timeout=30s
# ia.anthropic.version=2023-06-01

# Logging
quarkus.log.level=INFO
quarkus.log.category."com.joedayz".level=DEBUG
