# Configuración del puerto
quarkus.http.port=8080

# Configuración de Ollama
ia.ollama.base=${OLLAMA_BASE_URL:http://localhost:11434}
ia.ollama.model=${OLLAMA_MODEL:llama3.2}
ia.ollama.max-tokens=${OLLAMA_MAX_TOKENS:500}
ia.ollama.timeout=${OLLAMA_TIMEOUT:2m}

# Logging
quarkus.log.level=INFO
quarkus.log.category."com.joedayz".level=DEBUG
