spring.application.name=spring-rag-demo

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/rag_demo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring AI OpenAI Configuration
spring.ai.openai.api-key=${OPENAI_API_KEY:}
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.openai.embedding.options.dimensions=768

spring.ai.openai.chat.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini

# Spring AI PgVector Configuration
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.max-document-batch-size=10000
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.schema-validation=false
spring.ai.vectorstore.pgvector.table-name=vector_store

rag.source.document.path=docs/BASES+CLOUDF_20260224_175315_332.pdf
